KEYWORDS = [
    # Computer Science - Deep Learning & Neural Networks (40개)
    "deep learning",
    "neural network",
    "convolutional neural network",
    "recurrent neural network",
    "long short-term memory",
    "gated recurrent unit",
    "residual network",
    "densenet",
    "inception network",
    "mobilenet",
    "efficientnet",
    "squeeze and excitation",
    "attention mechanism",
    "self-attention",
    "cross-attention",
    "multi-head attention",
    "neural architecture search",
    "automl",
    "hyperparameter optimization",
    "batch normalization",
    "layer normalization",
    "dropout",
    "regularization",
    "weight decay",
    "gradient descent",
    "adam optimizer",
    "learning rate scheduling",
    "curriculum learning",
    "knowledge distillation",
    "pruning neural networks",
    "quantization",
    "model compression",
    "neural network interpretability",
    "adversarial robustness",
    "adversarial training",
    "domain adaptation",
    "multi-task learning",
    "continual learning",
    "catastrophic forgetting",
    "neural ordinary differential equations",
    
    # Computer Science - Transformers & LLMs (30개)
    "transformer",
    "large language model",
    "BERT",
    "GPT",
    "GPT-2",
    "GPT-3",
    "GPT-4",
    "T5",
    "BART",
    "RoBERTa",
    "ELECTRA",
    "ALBERT",
    "XLNet",
    "language model pretraining",
    "fine-tuning language models",
    "prompt engineering",
    "in-context learning",
    "chain of thought",
    "instruction tuning",
    "RLHF",
    "llama",
    "llama 2",
    "mistral",
    "claude",
    "palm",
    "gemini",
    "chatbot",
    "conversational AI",
    "dialogue generation",
    "controllable text generation",
    
    # Computer Science - Computer Vision (40개)
    "computer vision",
    "image classification",
    "object detection",
    "YOLO",
    "faster RCNN",
    "mask RCNN",
    "DETR",
    "image segmentation",
    "semantic segmentation",
    "instance segmentation",
    "panoptic segmentation",
    "U-Net",
    "DeepLab",
    "face recognition",
    "face detection",
    "facial landmark detection",
    "pose estimation",
    "human pose estimation",
    "hand pose estimation",
    "action recognition",
    "video classification",
    "video understanding",
    "optical flow",
    "visual tracking",
    "object tracking",
    "3D reconstruction",
    "structure from motion",
    "depth estimation",
    "monocular depth estimation",
    "stereo matching",
    "image super resolution",
    "image denoising",
    "image inpainting",
    "style transfer",
    "neural style transfer",
    "image-to-image translation",
    "medical image analysis",
    "satellite image analysis",
    "autonomous driving",
    "scene understanding",
    
    # Computer Science - Generative Models (25개)
    "generative adversarial network",
    "GAN",
    "StyleGAN",
    "CycleGAN",
    "Pix2Pix",
    "conditional GAN",
    "WGAN",
    "progressive GAN",
    "variational autoencoder",
    "VAE",
    "diffusion model",
    "denoising diffusion",
    "stable diffusion",
    "DALL-E",
    "imagen",
    "midjourney",
    "text-to-image generation",
    "image synthesis",
    "video generation",
    "3D generation",
    "NeRF",
    "neural radiance fields",
    "implicit neural representation",
    "generative model",
    "latent diffusion",
    
    # Computer Science - Multimodal Learning (20개)
    "multimodal learning",
    "vision and language",
    "CLIP",
    "ALIGN",
    "BLIP",
    "Flamingo",
    "visual question answering",
    "image captioning",
    "video captioning",
    "text-to-video generation",
    "audio-visual learning",
    "speech recognition",
    "automatic speech recognition",
    "text-to-speech",
    "speech synthesis",
    "cross-modal retrieval",
    "vision-language pretraining",
    "embodied AI",
    "multimodal fusion",
    "audio-visual synchronization",
    
    # Computer Science - Natural Language Processing (35개)
    "natural language processing",
    "machine translation",
    "neural machine translation",
    "question answering",
    "reading comprehension",
    "information retrieval",
    "document retrieval",
    "semantic search",
    "named entity recognition",
    "relation extraction",
    "information extraction",
    "knowledge graph",
    "knowledge graph embedding",
    "sentiment analysis",
    "emotion detection",
    "text classification",
    "text clustering",
    "topic modeling",
    "text summarization",
    "abstractive summarization",
    "extractive summarization",
    "paraphrase generation",
    "semantic textual similarity",
    "natural language inference",
    "coreference resolution",
    "dependency parsing",
    "constituency parsing",
    "semantic role labeling",
    "word sense disambiguation",
    "word embedding",
    "sentence embedding",
    "contextual embedding",
    "zero-shot learning NLP",
    "cross-lingual NLP",
    "low-resource NLP",
    
    # Computer Science - Reinforcement Learning (20개)
    "reinforcement learning",
    "deep reinforcement learning",
    "Q-learning",
    "deep Q-network",
    "policy gradient",
    "actor-critic",
    "proximal policy optimization",
    "trust region policy optimization",
    "soft actor-critic",
    "model-based reinforcement learning",
    "model-free reinforcement learning",
    "multi-agent reinforcement learning",
    "inverse reinforcement learning",
    "imitation learning",
    "offline reinforcement learning",
    "meta-reinforcement learning",
    "hierarchical reinforcement learning",
    "exploration in reinforcement learning",
    "reward shaping",
    "transfer learning in RL",
    
    # Computer Science - Graph Neural Networks (15개)
    "graph neural network",
    "graph convolutional network",
    "graph attention network",
    "message passing neural network",
    "graph representation learning",
    "node classification",
    "link prediction",
    "graph classification",
    "graph generation",
    "knowledge graph completion",
    "graph transformer",
    "temporal graph network",
    "heterogeneous graph",
    "graph pooling",
    "graph matching",
    
    # Computer Science - Recommendation Systems (12개)
    "recommendation system",
    "collaborative filtering",
    "matrix factorization",
    "content-based filtering",
    "neural collaborative filtering",
    "session-based recommendation",
    "sequential recommendation",
    "knowledge-aware recommendation",
    "cross-domain recommendation",
    "explainable recommendation",
    "conversational recommendation",
    "deep learning for recommendation",
    
    # Computer Science - Time Series & Forecasting (10개)
    "time series forecasting",
    "time series analysis",
    "temporal prediction",
    "sequence modeling",
    "anomaly detection time series",
    "multivariate time series",
    "transformer for time series",
    "LSTM time series",
    "financial forecasting",
    "demand forecasting",
    
    # Computer Science - Transfer Learning & Few-Shot (15개)
    "transfer learning",
    "domain adaptation",
    "domain generalization",
    "few-shot learning",
    "one-shot learning",
    "zero-shot learning",
    "meta-learning",
    "MAML",
    "prototypical networks",
    "matching networks",
    "metric learning",
    "contrastive learning",
    "self-supervised learning",
    "semi-supervised learning",
    "unsupervised learning",
    
    # Computer Science - Federated & Privacy (8개)
    "federated learning",
    "privacy-preserving machine learning",
    "differential privacy",
    "secure multi-party computation",
    "homomorphic encryption",
    "decentralized learning",
    "split learning",
    "vertical federated learning",
    
    # Computer Science - Explainability & Fairness (10개)
    "explainable AI",
    "interpretable machine learning",
    "feature importance",
    "saliency map",
    "attention visualization",
    "LIME",
    "SHAP",
    "fairness in machine learning",
    "bias detection",
    "algorithmic fairness",
    
    # Computer Science - Systems & Efficiency (12개)
    "distributed systems",
    "distributed training",
    "data parallelism",
    "model parallelism",
    "pipeline parallelism",
    "cloud computing",
    "edge computing",
    "edge AI",
    "mobile deep learning",
    "GPU optimization",
    "efficient neural network",
    "green AI",
    
    # Robotics (10개)
    "robotics",
    "robot learning",
    "manipulation",
    "robot grasping",
    "motion planning",
    "SLAM",
    "visual servoing",
    "human-robot interaction",
    "sim-to-real",
    "robot navigation",
    
    # Physics (20개)
    "quantum computing",
    "quantum machine learning",
    "quantum algorithm",
    "quantum mechanics",
    "condensed matter physics",
    "high energy physics",
    "particle physics",
    "astrophysics",
    "cosmology",
    "dark matter",
    "gravitational waves",
    "black hole",
    "string theory",
    "statistical mechanics",
    "plasma physics",
    "nuclear physics",
    "quantum field theory",
    "lattice QCD",
    "neutrino physics",
    "dark energy",
    
    # Mathematics (15개)
    "optimization",
    "convex optimization",
    "stochastic optimization",
    "combinatorial optimization",
    "linear programming",
    "differential equations",
    "partial differential equations",
    "numerical methods",
    "graph theory",
    "algebraic topology",
    "category theory",
    "probability theory",
    "random matrix theory",
    "computational geometry",
    "dynamical systems",
    
    # Statistics (10개)
    "statistical inference",
    "Bayesian inference",
    "Bayesian optimization",
    "causal inference",
    "causal discovery",
    "statistical learning theory",
    "hypothesis testing",
    "survival analysis",
    "variational inference",
    "Monte Carlo methods",
    
    # Quantitative Biology (15개)
    "computational biology",
    "bioinformatics",
    "genomics",
    "proteomics",
    "protein structure prediction",
    "AlphaFold",
    "drug discovery",
    "molecular dynamics",
    "systems biology",
    "single-cell analysis",
    "gene expression",
    "protein-protein interaction",
    "sequence alignment",
    "phylogenetics",
    "cancer genomics",
    
    # Quantitative Finance & Economics (8개)
    "algorithmic trading",
    "portfolio optimization",
    "risk management",
    "option pricing",
    "market prediction",
    "econometrics",
    "game theory",
    "mechanism design",
    
    # Electrical Engineering (5개)
    "signal processing",
    "wireless communication",
    "5G networks",
    "beamforming",
    "channel estimation",
]

# 총 400개 키워드
